// <auto-generated />
namespace SignatureRequests.DataAccessHandlers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:SignatureRequests/SignatureRequests.DataAccessHandlers/Migrations/201907312129190_ForDeletingBox.Designer.cs
    public sealed partial class ForDeletingBox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForDeletingBox));
        
        string IMigrationMetadata.Id
        {
            get { return "201907312129190_ForDeletingBox"; }
=======
    public sealed partial class _new : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_new));
        
        string IMigrationMetadata.Id
        {
            get { return "201908011513577_new"; }
>>>>>>> 8f728441dfa3aacfedb955df2993d90fdb35dbc4:SignatureRequests/SignatureRequests.DataAccessHandlers/Migrations/201908011513577_new.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
