// <auto-generated />
namespace SignatureRequests.DataAccessHandlers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:SignatureRequests/SignatureRequests.DataAccessHandlers/Migrations/201907181911341_goaway.Designer.cs
    public sealed partial class goaway : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(goaway));
        
        string IMigrationMetadata.Id
        {
            get { return "201907181911341_goaway"; }
=======
    public sealed partial class NewMigrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMigrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201907191355427_NewMigrate"; }
>>>>>>> b4871907690c843ce4541cff834ef340489a3737:SignatureRequests/SignatureRequests.DataAccessHandlers/Migrations/201907191355427_NewMigrate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
